logging:
  level:
    org.springframework: false
    org.apache: false
    org.hibernate: false
server:
  port: 8082
  address: localhost
spring:
  profiles:
    active:
    - dev
  main:
    banner-mode: 'off'
  datasource:
    url: jdbc:mysql://localhost:3306/scalton-product?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root
    dbcp2:
      validation-query: SELECT 1
      test-on-borrow: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
          use_query_cache: false
        generate_statistics: false
  rabbitmq:
      hostname: rabbitmq
      username: test
      password: password
axon:
  eventhandling:
    processors:
      statistics:
        source: statisticsQueue